# Directories to symlink with GNU Stow
[stow]
aerospace
bat
btop
containers
cursor
fish
gh-dash
git
kitty
lazygit
nvim
opencode
starship
tmux
worktrunk
zsh

# APT packages to install
[apt-deps]
build-essential
ca-certificates
curl
libcairo2-dev
libdbus-glib-1-dev
libgirepository1.0-dev
libsystemd-dev
pkg-config
python3-pip
stow
uidmap

# Extra APT repositories to add
[apt-repos]

# Pre-installed APT packages to remove
[apt-remove]
python3
python3.10
python3-minimal
python3.10-minimal
