[cmd_duration]
format = '[$duration](bold yellow)'

[directory]
truncate_to_repo = false
truncation_length = 0

[gcloud]
disabled = true

[aws]
disabled = true

[git_branch]
symbol = ""
format = "[$symbol $branch ]($style)"

[git_metrics]
disabled = true

[git_status]
ahead = '[⇡${count}](green)'
diverged = '[⇡${ahead_count}](green)[⇣${behind_count}](red)'
behind = '[⇣${count}](red)'
staged = '[+$count](green)'
modified = '[!$count](yellow)'
deleted = '[-$count](red)'
untracked = '[?$count](blue)'
style = 'white'
